Fix build failure for ptp-notification images
Fixes a pip install error when building the notificationservice-base,
notificationclient-base and locationservice-base images:
ModuleNotFoundError: No module named 'setuptools_rust'

It appears that an upstream change to oslo.messaging has caused the
setuptools_rust dependency to not be found. Updating pip3 before
installing additional modules resolves this issue.

Closes-Bug: 1988854

Signed-off-by: Cole Walker <cole.walker@windriver.com>
Change-Id: If568191b3e8feb1c23bdbc4168e495395567846d